import { FileDown } from 'lucide-react'
import { Link, Outlet, ScrollRestoration } from 'react-router'
import { BackToTop } from './BackToTop'
import { GitHubIcon } from './GitHubIcon'
import { ThemeToggle } from './ThemeToggle'

const REPO_URL = 'https://github.com/edriso/tldr'
// Generated by CI on every deploy (see .github/workflows/deploy.yml).
const PDF_URL = `${import.meta.env.BASE_URL}tldr.pdf`

export function Layout() {
  return (
    <div className="flex min-h-screen flex-col">
      <header className="sticky top-0 z-10 border-b border-zinc-200 bg-zinc-50/85 backdrop-blur dark:border-zinc-800 dark:bg-zinc-950/85">
        <div className="mx-auto flex w-full max-w-5xl items-center justify-between px-4 py-3">
          <Link to="/" className="font-mono text-lg font-bold tracking-tight">
            <span className="text-zinc-900 dark:text-zinc-50">tl</span>
            <span className="text-accent">;</span>
            <span className="text-zinc-900 dark:text-zinc-50">dr</span>
          </Link>
          <div className="flex items-center gap-1">
            <a
              href={PDF_URL}
              download="tldr.pdf"
              aria-label="Download the whole guide as a PDF"
              title="Download as PDF"
              className="rounded-full p-2 text-zinc-500 transition hover:bg-zinc-200/60 hover:text-zinc-900 dark:text-zinc-400 dark:hover:bg-zinc-800 dark:hover:text-zinc-50"
            >
              <FileDown size={18} />
            </a>
            <a
              href={REPO_URL}
              target="_blank"
              rel="noreferrer"
              aria-label="View source on GitHub"
              className="rounded-full p-2 text-zinc-500 transition hover:bg-zinc-200/60 hover:text-zinc-900 dark:text-zinc-400 dark:hover:bg-zinc-800 dark:hover:text-zinc-50"
            >
              <GitHubIcon size={18} />
            </a>
            <ThemeToggle />
          </div>
        </div>
      </header>

      <main className="mx-auto w-full max-w-5xl flex-1 px-4 py-8">
        <Outlet />
      </main>

      <footer className="border-t border-zinc-200 py-6 dark:border-zinc-800">
        <p className="mx-auto max-w-5xl px-4 font-mono text-xs text-zinc-500 dark:text-zinc-400">
          tl;dr : short dev notes that stick. One analogy, one example, one use case.
        </p>
      </footer>

      <BackToTop />
      <ScrollRestoration />
    </div>
  )
}
